# Generated by Django 2.2 on 2019-04-19 18:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tytuł')),
                ('body', models.TextField(blank=True, verbose_name='Tekst')),
                ('author', models.CharField(max_length=150, null=True, verbose_name='Autor')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data dodania')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Czy widoczny?')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title'], verbose_name='Uproszczona nazwa')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Category', verbose_name='Kategoria')),
            ],
        ),
    ]
