# Generated by Django 2.2 on 2019-04-19 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190414_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data dodania'),
        ),
    ]
