# Generated by Django 2.2 on 2019-04-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20190419_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Czy widoczny?'),
        ),
    ]
