# Generated by Django 2.2 on 2019-04-19 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "__first__"),
        ('articles', '0008_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Category', verbose_name='Kategoria'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
